export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';
export const TOGGLE_BARS = 'TOGGLE_BARS';

export const SEARCH_INIT ='SEARCH_INIT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const POKEMON_LIST_INIT = 'POKEMON_LIST_INIT';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';
export const POKEMON_LIST_FILTER = 'POKEMON_LIST_FILTER';
export const POKEMON_LIST_CLEAR_FILTER = 'POKEMON_LIST_CLEAR_FILTER';

export const EVOLUTION_IMAGE_INIT = 'EVOLUTION_IMAGE_INIT';
export const EVOLUTION_IMAGE_SUCCESS = 'EVOLUTION_IMAGE_SUCCESS';
export const EVOLUTION_IMAGE_FAIL = 'EVOLUTION_IMAGE_FAIL';

export const CLEAR_DETAILS = 'CLEAR_DETAILS';